// Generated by gencpp from file rs_stream/CompressedRGBD.msg
// DO NOT EDIT!


#ifndef RS_STREAM_MESSAGE_COMPRESSEDRGBD_H
#define RS_STREAM_MESSAGE_COMPRESSEDRGBD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rs_stream
{
template <class ContainerAllocator>
struct CompressedRGBD_
{
  typedef CompressedRGBD_<ContainerAllocator> Type;

  CompressedRGBD_()
    : header()
    , rgb()
    , depth()  {
    }
  CompressedRGBD_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rgb(_alloc)
    , depth(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _rgb_type;
  _rgb_type rgb;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _depth_type;
  _depth_type depth;





  typedef boost::shared_ptr< ::rs_stream::CompressedRGBD_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rs_stream::CompressedRGBD_<ContainerAllocator> const> ConstPtr;

}; // struct CompressedRGBD_

typedef ::rs_stream::CompressedRGBD_<std::allocator<void> > CompressedRGBD;

typedef boost::shared_ptr< ::rs_stream::CompressedRGBD > CompressedRGBDPtr;
typedef boost::shared_ptr< ::rs_stream::CompressedRGBD const> CompressedRGBDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rs_stream::CompressedRGBD_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rs_stream::CompressedRGBD_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rs_stream::CompressedRGBD_<ContainerAllocator1> & lhs, const ::rs_stream::CompressedRGBD_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rgb == rhs.rgb &&
    lhs.depth == rhs.depth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rs_stream::CompressedRGBD_<ContainerAllocator1> & lhs, const ::rs_stream::CompressedRGBD_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rs_stream

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rs_stream::CompressedRGBD_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rs_stream::CompressedRGBD_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rs_stream::CompressedRGBD_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rs_stream::CompressedRGBD_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rs_stream::CompressedRGBD_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rs_stream::CompressedRGBD_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rs_stream::CompressedRGBD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da764014b2d5d185b296733c983338cb";
  }

  static const char* value(const ::rs_stream::CompressedRGBD_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda764014b2d5d185ULL;
  static const uint64_t static_value2 = 0xb296733c983338cbULL;
};

template<class ContainerAllocator>
struct DataType< ::rs_stream::CompressedRGBD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rs_stream/CompressedRGBD";
  }

  static const char* value(const ::rs_stream::CompressedRGBD_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rs_stream::CompressedRGBD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8[] rgb\n"
"uint8[] depth\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rs_stream::CompressedRGBD_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rs_stream::CompressedRGBD_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rgb);
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CompressedRGBD_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rs_stream::CompressedRGBD_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rs_stream::CompressedRGBD_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rgb[]" << std::endl;
    for (size_t i = 0; i < v.rgb.size(); ++i)
    {
      s << indent << "  rgb[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.rgb[i]);
    }
    s << indent << "depth[]" << std::endl;
    for (size_t i = 0; i < v.depth.size(); ++i)
    {
      s << indent << "  depth[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.depth[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RS_STREAM_MESSAGE_COMPRESSEDRGBD_H
